// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadWriteExcelSql.Models;

#nullable disable

namespace ReadWriteExcelSql.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReadWriteExcelSql.Models.UpExcel", b =>
                {
                    b.Property<int>("ExcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Col1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Col4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExcelId");

                    b.ToTable("UpExcel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
